branches:
  only:
    - master

language: groovy
jdk:
  - openjdk8

addons:
  apt:
    packages:
      - sox
      - speech-tools

script: ./gradlew check --info

cache:
  directories:
    - $HOME/.gradle/caches/modules-2
    - $HOME/.gradle/wrapper
