sudo: false

branches:
  only:
    - master

language: groovy
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8

addons:
  apt:
    packages:
    - sox
    - speech-tools

before_install:
  - JAVA_HOME=$(jdk_switcher home openjdk8) ./gradlew

script: ./gradlew check --info

env:
  - LEGACY_PRAAT=1

cache:
  directories:
    - $HOME/.gradle/caches/modules-2
    - $HOME/.gradle/wrapper
