branches:
  only:
    - master

language: groovy
jdk:
  - openjdk8
  - openjdk11
  - openjdk13

addons:
  apt:
    packages:
      - sox
      - speech-tools

script: ./gradlew check

cache:
  directories:
    - $HOME/.gradle/caches/modules-2
    - $HOME/.gradle/wrapper
